- name: installing packages
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
   - yum:
      name: bind-utils
     when: ansible_os_family == “RedHat”
   - apt:
      name: dnsutils
     when: ansible_os_family == “Debian”